### ISSUE TITLE
just some praise

### ISSUE THREAD

**Issue by davephillips** [AlliewayAudio/AlliewayAudio_Freebies#4]
Greetings ! I've been working with Chilly Cheese on VCV Rack v2, starting to learn how the module is organized. I'm studying various YouTube tutorials about the Cold Mac hardware, and I'm beginning to appreciate what it can do. I don't know the original hardware at all, but it seems you've got it all in Chilly Cheese. Thank you for the excellent port, I look forward to much exploration. I love deep stuff. :)

Best regards,

Dave Phillips

**Comment by AlliewayAudio** [comment]
So happy you like the plugin Dave! Please let me know if you have any issues that pop up, and keep an eye out since I have 3 new original modules which will be dropping on the Library in the next few days with a similar playful experimental vibe to Chilly Cheese, as well as some addition free+paid modules on the horizon ^_^

Appreciate you,
~Allie
